Traceback (most recent call last):
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/rblack/_dev/live-2022/.direnv/python-3.10.4/lib/python3.10/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xu,yu,xl,yl = simplexCamber(xa,ya,ma,0.005)
f = plt.figure()
f.set_figwidth(11)
f.set_figheight(2)
plt.ylim(top=0.15, bottom = -0.05)
plt.xlim(left=-0.05,right=1.05)
plt.plot(xu,yu)
plt.plot(xl,yl)
plt.plot(xp,yp)
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/ws/5h_x4h713cg8w0jmrm5_tfzc0000gn/T/ipykernel_47325/727194808.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mxu[0m[0;34m,[0m[0myu[0m[0;34m,[0m[0mxl[0m[0;34m,[0m[0myl[0m [0;34m=[0m [0msimplexCamber[0m[0;34m([0m[0mxa[0m[0;34m,[0m[0mya[0m[0;34m,[0m[0mma[0m[0;34m,[0m[0;36m0.005[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mf[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mf[0m[0;34m.[0m[0mset_figwidth[0m[0;34m([0m[0;36m11[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mf[0m[0;34m.[0m[0mset_figheight[0m[0;34m([0m[0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mplt[0m[0;34m.[0m[0mylim[0m[0;34m([0m[0mtop[0m[0;34m=[0m[0;36m0.15[0m[0;34m,[0m [0mbottom[0m [0;34m=[0m [0;34m-[0m[0;36m0.05[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'xa' is not defined
NameError: name 'xa' is not defined

